prezi/spaghetti

- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/PackageApplication.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/internal/AbstractBundleModuleTask.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/internal/AbstractSpaghettiTask.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/internal/ModuleBundleLookup.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/bundle/ModuleBundleLoader.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/bundle/ModuleBundleSet.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/bundle/internal/DefaultModuleBundleSet.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/definition/ModuleConfiguration.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/definition/ModuleConfigurationParser.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/definition/internal/DefaultModuleConfiguration.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/packaging/ApplicationPackageParameters.java
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/bundle/internal/DefaultModuleBundleSetTest.groovy
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/config/ModuleConfigurationParserTest.groovy
- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/HaxeHeaderGenerator.groovy
- spaghetti-kotlin-support/src/main/groovy/com/prezi/spaghetti/kotlin/KotlinHeaderGenerator.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptHeaderGenerator.groovy
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/AbstractCommand.java
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/AbstractDefinitionAwareCommand.java
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/AbstractSpaghettiCommand.java
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/BundleModuleCommand.java
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/PackageApplicationCommand.java
It seemed like a good idea at the time (#141) to allow access to transitive modules as well. However, it causes further problems. Here's why:
We need to record the names of each module in the final, packaged JavaScript that the code inside has access to, so that RequireJS/Node JS can load them. If we allow access to transitive dependencies, the names of those modules need to be wired in as well. Like so:
```js
define(["my.direct.dependency", "my.transitive.dependency"], function() { /* ... */ });
```
This has some unwanted consequences: even if my module's code does not access the `my.transitive.dependency` module at all, RequireJS will still try to load it, because it's listed as a dependency. However, if `my.direct.dependency` is changed, and it doesn't depend on …
> Transitive blocking

- gradle-spaghetti-haxe-plugin/src/main/java/com/prezi/spaghetti/haxe/gradle/SpaghettiHaxePlugin.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/GenerateHeaders.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/SpaghettiBasePlugin.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/SpaghettiPlugin.java
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/internal/SpaghettiExtension.java
- gradle-spaghetti-typescript-plugin/src/main/java/com/prezi/spaghetti/typescript/gradle/SpaghettiTypeScriptPlugin.java
- gradle-spaghetti-typescript-plugin/src/test/groovy/com/prezi/spaghetti/typescript/gradle/SpaghettiTypeScriptPluginTest.groovy
So there should be a `testModules` configuration (and a symmetric `testModulesObf`), where the user can add test Spaghetti dependencies.
> Test tasks should run with a test configuration

- gradle-spaghetti-haxe-plugin/src/main/java/com/prezi/spaghetti/haxe/gradle/NodeTestWithSpaghetti.java
- gradle-spaghetti-haxe-plugin/src/main/java/com/prezi/spaghetti/haxe/gradle/SpaghettiHaxePlugin.java
- gradle-spaghetti-haxe-plugin/src/main/resources/munit_node_resources/munit_node_runner.js
Enable munit tests to run in node.
This pull-request relies on these changes in the `gradle-haxe-plugin`: https://github.com/prezi/gradle-haxe-plugin/pull/37
The goal of this is to be able to run haxe munit tests on not only the browser but on node too. The default runner remains the browser, buth with the `-Pmunit.usenode` flag the tests are run in a node environment (and not in the browser).
The new implementation does not interfere with the old one, there is a different working directory with a different `HaxeBinary`, compile and runner tasks.
> Munit node

- gradle-spaghetti-haxe-plugin/src/main/resources/munit_node_resources/munit_node_runner.js
This is to prepare the js test environment. We copy the window object's properties (.document, addEventListener etc) to the global node.js object.
> copy stuff from the window object to the global object

- spaghetti-api/src/main/java/com/prezi/spaghetti/generator/GeneratorUtils.java
- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/HaxeDefinitionIteratorVisitor.groovy
- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/HaxeEnumGeneratorVisitor.groovy
- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/HaxeHeaderGenerator.groovy
- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/access/HaxeModuleAccessorGeneratorVisitor.groovy
- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/impl/HaxeModuleProxyGeneratorVisitor.groovy
- spaghetti-haxe-support/src/test/groovy/com/prezi/spaghetti/haxe/HaxeEnumGeneratorVisitorTest.groovy
- spaghetti-kotlin-support/src/main/groovy/com/prezi/spaghetti/kotlin/KotlinDefinitionIteratorVisitor.groovy
- spaghetti-kotlin-support/src/main/groovy/com/prezi/spaghetti/kotlin/KotlinEnumGeneratorVisitor.groovy
- spaghetti-kotlin-support/src/main/groovy/com/prezi/spaghetti/kotlin/KotlinHeaderGenerator.groovy
- spaghetti-kotlin-support/src/main/groovy/com/prezi/spaghetti/kotlin/access/KotlinModuleAccessorGeneratorVisitor.groovy
- spaghetti-kotlin-support/src/main/groovy/com/prezi/spaghetti/kotlin/impl/KotlinModuleProxyGeneratorVisitor.groovy
- spaghetti-kotlin-support/src/test/groovy/com/prezi/spaghetti/kotlin/KotlinEnumGeneratorVisitorTest.groovy
- spaghetti-support-test-harness/src/main/resources/TestModule.module
- spaghetti-support-test-harness/src/main/resources/app.js
- spaghetti-support-test-harness/src/main/resources/dependency.js
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptDefinitionIteratorVisitor.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptEnumGeneratorVisitor.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptHeaderGenerator.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/access/TypeScriptModuleAccessorGeneratorVisitor.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/impl/TypeScriptModuleProxyGeneratorVisitor.groovy
This makes enums robust against reordering as discussed in #200.
> Implement definition of foreign enums by reference to original definition in foreign module

- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/ObfuscateModule.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/ModuleObfuscator.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/ObfuscationParameters.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/internal/ClosureCompiler.java
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/BundleModuleCommand.java
Lets the user choose between levels of optimising compilation: whitespace only, simple, and advanced.
With a choice between only advanced and no optimisation/obfuscation, developers have no option other than falling back to no optimisations when obfuscation causes problems.
Giving more granular control over compilation levels should ease this problem.
> Add support for configuring Closure compilation level

- settings.gradle
Remove `spaghett-kotlin-support` from `settings.gradle`'s project list, because it no longer exists.
> Remove kotlin-support from settings.gradle

- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/access/TypeScriptModuleAccessorGeneratorVisitor.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/type/enums/TypeScriptOpaqueEnumGeneratorVisitor.groovy
- spaghetti-typescript-support/src/test/groovy/com/prezi/spaghetti/typescript/access/TypeScriptModuleAccessorGeneratorVisitorTest.groovy
* Don't use `export class` in generated headers, because it generates lots of redundant JS output.
* Use `declare` for transitive enums, because they don't have any members and so no JS should be output for it.
> Optimize typescript headers

- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/internal/SymbolCollectVisitor.java
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/obfuscation/SymbolCollectVisitorTest.groovy
In order to expose consts on obfuscated modules, their names need to be added to the set of protected symbols.
> Add collector for const struct names

- build.gradle
Official website is now `groovy-lang.org`
> Fix groovy doc location

- spaghetti-core/src/main/java/com/prezi/spaghetti/packaging/internal/UmdModuleWrapper.java
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/packaging/UmdModuleWrapperTest.groovy
Support browser global modules.
The term UMD refers a JS module which can be loaded three ways:
* AMD: using requirejs
* CommonJS: in Node
* Browser Globals: attached directly to the Window
If we say we support UMD, we should support the last case as well.
Also the prezipage module in Prezi could benefit from this. Currently we are using a hack to work around the Spaghetti wrapper because there is no support for attaching directly to the window.
> UMD supports browser globals.

- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/ObfuscateModule.java
This is only a quickfix, ideally we should only add compilerPath to the inputs when it's needed
> fix obfuscate module: make compiler path optional input

- spaghetti-haxe-support/src/main/groovy/com/prezi/spaghetti/haxe/type/enums/HaxeEnumGeneratorVisitor.groovy
- spaghetti-haxe-support/src/test/groovy/com/prezi/spaghetti/haxe/type/enums/HaxeEnumGeneratorVisitorTest.groovy
Other languages than js could not compile.
Added conditional compile flag for haxe `__js__` code, so it can be compiled to for example Java.
> Fix enum generation for haxe

- spaghetti-core/src/main/ts/tsAstParser.ts
- spaghetti-core/src/main/ts/tsconfig.json
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/tsast/TypeScriptAstParserServiceTest.groovy
* Checks syntax of inlined modules, not just the main `*.module.ts`
* Doesn't allow relative imports inside the inlined modules
* Removes duplicate imports from the inlined module (if the same import is already in the `*.module.ts`
> Improve merging of .d.ts files

- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/internal/ClosureCompiler.java
We tried to solve a different problem by setting the language input of closure compiler to ES6 (https://github.com/prezi/spaghetti/pull/249) but it didn't turn out well so I set it back to ES5.
> Revert closure compiler language input to ES5

- build.gradle
- gradle-spaghetti-plugin/src/main/java/com/prezi/spaghetti/gradle/ObfuscateModule.java
- gradle-spaghetti-typescript-plugin/src/main/java/com/prezi/spaghetti/typescript/gradle/internal/ClosureConcatenateTask.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/ClosureTarget.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/ModuleObfuscator.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/ObfuscationParameters.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/internal/ClosureCompiler.java
- spaghetti/src/main/java/com/prezi/spaghetti/cli/commands/BundleModuleCommand.java
**Needs major bump.**
Changed `sourceCompatibility` and `targetCompatibility` to `1.8`.
Closure compiler now has a target property:
* `es5` or `es6`
* by default it's `es5` to remain backward compatible
Bumped closure compiler to handle es6 classes.
Flags required for es6:
* `--emit_use_strict false`: so that Closure does not add `"use strict";` to the start of output. It would break module wrapping.
* `--rewrite_polyfills false`: so that Closure does not generate polyfills. It would break module wrapping. We use Closure only for obfuscation, concatenation, if we use polyfills it should already be in the code.
> Introduce es6 target

- closure-compiler-wrapper/build.gradle
- closure-compiler-wrapper/src/main/java/com/prezi/spaghetti/closure/ClosureWrapper.java
- gradle-spaghetti-typescript-plugin/src/main/java/com/prezi/spaghetti/typescript/gradle/internal/ClosureConcatenateTask.java
- settings.gradle
- spaghetti-core/build.gradle
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/internal/ClosureCompiler.java
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/obfuscation/ClosureCompilerTest.groovy
Instead of calling Google Closure Compiler from the command line use closure-compiler-wrapper, a new small Java application that calls Google Closure Compiler's Java API directly.
This allows:
* Fine-grained control of error messages so we can ignore undefined var errors, but still throw an error on circular references for es6 modules.
* Fine-grained control over compilation level. We had to move the concat task to `WHITESPACE_ONLY` mode because it was messing up obfuscation by removing quotes from symbols that should be protected. Using the Java API we can go back to `SIMPLE_OPTIMIZATIONS` with `options.setConvertToDottedProperties(false);` to avoid this issue.
The obfuscation task still uses Google Closure Compiler from the command line, but if this change works in boxfish without …
> Closure java api wrapper

- closure-compiler-wrapper/src/main/java/com/prezi/spaghetti/closure/Args.java
- closure-compiler-wrapper/src/main/java/com/prezi/spaghetti/closure/ClosureWrapper.java
- closure-compiler-wrapper/src/main/java/com/prezi/spaghetti/closure/FilteringErrorManager.java
- gradle-spaghetti-typescript-plugin/src/main/java/com/prezi/spaghetti/typescript/gradle/internal/ClosureConcatenateTask.java
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/obfuscation/ClosureCompilerTest.groovy
It turns out that Closure Compiler can correctly catch the case that ES6 or commonjs modules are included in a bad order and a static reference (ie. class interitance, or other top level initialization) becomes undefined. The problem was that in addition to this, Closure Compiler reported *all* circular references as invalid early references (with the exact same message "Variable referenced before declaration").
Finally I have figured out how to ignore the latter (we should permit circular references) while still catching the static initializations which will be undefined. I do this by subclassing the compiler's ErrorManager and dropping an error being reports which matches a patter in the AST. The generated variable names (ie. "$$module$") are quite unique and predictable and so the …
> Filter circular reference closure errors

- closure-compiler-wrapper/build.gradle
- closure-compiler-wrapper/src/main/java/com/prezi/spaghetti/closure/ClosureWrapper.java
* Update to ClosureCompiler v20180716 to fix `SyntaxError` in obfuscated code. (see: https://github.com/google/closure-compiler/issues/3019)
* Disables minification and renaming for local development debugging.
> Fix closure obfuscation

- closure-compiler-wrapper/src/main/java/com/prezi/spaghetti/closure/ClosureWrapper.java
After obfuscation + wrapping we can end up with unusable modules like https://client-js.prezi.com/release/lib/prezi.engine.dom/33.0-1682-g5cb4d31/prezi.engine.dom.js
Problematic part:
```
var moduleImpl = (function() {
return 'use strict';
module(function(K) {
```
> Remove "use strict" from obfuscated js

- gradle-spaghetti-typescript-plugin/src/main/java/com/prezi/spaghetti/typescript/gradle/internal/ClosureConcatenateTask.java
Before this change, accessing values from a transient dependency would compile successfully but then fail at runtime.
> Don't generate closure bundle accessors for transient dependencies

- spaghetti-core/src/main/ts/tsAstParser.ts
- spaghetti-core/src/test/groovy/com/prezi/spaghetti/tsast/TypeScriptAstParserServiceTest.groovy
Plugin api uses many types like this:
```
export type ElementReference = {uiElementId: string} | {preziElementId?: string} | {virtualElementId: "viewport"};
```
Since these are not interfaces, the attributes names were not protected from obfuscation.
> Protect attributes in type aliases from obfuscation

- gradle-spaghetti-typescript-plugin/src/main/java/com/prezi/spaghetti/typescript/gradle/internal/ClosureConcatenateTask.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/ast/internal/parser/SimpleTypeScriptDefinitionParser.java
- spaghetti-core/src/main/java/com/prezi/spaghetti/obfuscation/internal/ClosureCompiler.java
- spaghetti-support-test-harness/src/main/resources/DependencyModule.module.d.ts
- spaghetti-support-test-harness/src/main/resources/TestModule.module.d.ts
- spaghetti-support-test-harness/src/main/resources/TestModule.module.ts
- spaghetti-typescript-support/src/integTest/groovy/com/prezi/spaghetti/typescript/TypeScriptGeneratorIntegrationTest.groovy
- spaghetti-typescript-support/src/integTest/module/src/TestModule.ts
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptDefinitionImportVisitor.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptHeaderGenerator.groovy
- spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/TypeScriptJavaScriptBundleProcessor.groovy
- spaghetti-typescript-support/src/test/groovy/com/prezi/spaghetti/typescript/TypeScriptDefinitionImportVisitorTest.groovy
- spaghetti-typescript-support/src/test/groovy/com/prezi/spaghetti/typescript/TypeScriptJavaScriptBundleProcessorTest.groovy
Generate two kinds of typescript headers in the same file for backward compatibility:
* Ambient global: `declare module prezi.geometry { ... }`
* Can be used directly `prezi.geometry.Rectangle`
* Ambient commonjs: `declare module "prezi.geometry" { ... }`
* Can be used via es6 import: `import { Rectangle } from "prezi.geometry"`
This allows both commonJs and global accessors to work in the same file, easing the transition to commonjs imports.
This PR also reverts the conversion of all module names from dots to underscores (from Typescript's perspective). This makes it easier to match file names on disk with the imported string name.
> Backwards compat headers
